apiVersion: v1
kind: ServiceAccount
metadata:
  name: vhsm-service-account
  namespace: vhsm
  labels:
    app: vhsm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vhsm-role
  namespace: vhsm
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vhsm-rolebinding
  namespace: vhsm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vhsm-role
subjects:
- kind: ServiceAccount
  name: vhsm-service-account
  namespace: vhsm
